This is probably a bad idea

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -1,57 +1,67 @@
 CASE_SENSITIVE="true"
 if [[ `uname` == 'Linux'  ]]
 then
-    export LINUX=1
-    export GNU_USERLAND=1
-    export SHELL="/usr/bin/zsh"
-    if [[ -e "/usr/bin/tmux-next" ]]
-    then
-        export TMUX_PATH="/usr/bin/tmux-next"
-    else
-        export TMUX_PATH="/usr/bin/tmux"
-    fi
+  export LINUX=1
+  export GNU_USERLAND=1
+  export SHELL="/usr/bin/zsh"
+  if [[ -e "/usr/bin/tmux-next" ]]
+  then
+    export TMUX_PATH="/usr/bin/tmux-next"
+  else
+    export TMUX_PATH="/usr/bin/tmux"
+  fi
 else
-    export LINUX=
+  export LINUX=
 fi
 
 if [[ `uname` == 'Darwin'  ]]
 then
-    export OSX=1
-    export SHELL="/usr/local/bin/zsh"
-    export TMUX_PATH="/usr/local/bin/tmux"
+  export OSX=1
+  export SHELL="/usr/local/bin/zsh"
+  export TMUX_PATH="/usr/local/bin/tmux"
 else
-    export OSX=
+  export OSX=
 fi
 
 if [[ "$SSH_CONNECTION" ]]
 then
-    export REMOTE_SESSION=1
+  export REMOTE_SESSION=1
 else
-    export REMOTE_SESSION=
-fi
-
-# Detect Homebrew GNU userland installation
-if [[ "$OSX" == "1"  ]]
-then
-    if [[ -e /usr/local/opt/coreutils  ]]
-    then
-        export GNU_USERLAND=1
-    fi
+  export REMOTE_SESSION=
 fi
 
 export TRUE_COLOR=`$TMUX_PATH info | grep Tc | grep -o true`
 
 autoload run-help
 HELPDIR=/usr/local/share/zsh/help
-if [[ "$OSX" == "1" ]]
+
+export PATH="$HOME/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin"
+
+if [[ -e /usr/local/bin/brew ]]
 then
-    export PATH="$HOME/.local/bin:/usr/local/opt/python/libexec/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/opt/FDK/Tools/osx:/Library/TeX/texbin/"
+  export HOMEBREW_PREFIX="/usr/local"
+  export HOMEBREW_CELLAR="/usr/local/Cellar"
+  export HOMEBREW_REPOSITORY="/usr/local/Homebrew"
+  export MANPATH="/usr/local/share/man:$MANPATH"
+  export INFOPATH="/usr/local/share/info:$INFOPATH"
+  if [[ -e /usr/local/opt/coreutils ]]; then export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"; fi
+  if [[ -e /usr/local/opt/gnu-tar ]]; then export PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"; fi
+  if [[ -e /usr/local/opt/llvm ]]; then export PATH="/usr/local/opt/llvm/bin:$PATH"; fi
+  if [[ -e /usr/local/opt/python ]]; then export PATH="/usr/local/opt/python/libexec/bin:$PATH"; fi
+  export PATH="$HOME/.local/bin:$PATH"
 else
-    export PATH="$HOME/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin"
 fi
 
+fpath+=${ZDOTDIR:-~}/.zsh_functions
 export DOTFILES=$HOME/.dotfiles
 source $DOTFILES/zsh/private.zsh
+
+# google-cloud-sdk (homebrew)
+source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc'
+source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'
+
+# source '/usr/local/opt/asdf/asdf.sh'
+# source '/usr/local/opt/asdf/etc/bash_completion.d/asdf.bash'
 
 source $HOME/antigen.zsh
 antigen init $HOME/.antigenrc
@@ -74,55 +84,60 @@ alias less='less -R'
 export LESS='-R'
 export LESSOPEN='|~/.lessfilter %s'
 
-alias yolo='git commit -m "$(curl -s https://whatthecommit.com/index.txt)"'
+alias yolo='git commit -am "$(curl -s https://whatthecommit.com/index.txt)"'
 
 if [[ -e `which nvim` ]]
 then
-    alias vim=nvim
-    export GIT_EDITOR=nvim
-    export VISUAL=nvim
-    export EDITOR=nvim
+  alias vim=nvim
+  export GIT_EDITOR=nvim
+  export VISUAL=nvim
+  export EDITOR=nvim
 else
-    export GIT_EDITOR=vim
-    export VISUAL=vim
-    export EDITOR=vim
+  export GIT_EDITOR=vim
+  export VISUAL=vim
+  export EDITOR=vim
 fi
 
-# google-cloud-sdk (homebrew)
-source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc'
-source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'
+ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=8'
 
-ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=10'
-
-precmd() {
-    tmux rename-window  `/usr/local/bin/super_pwd $("pwd")`
+export SHORT_PWD="$(/usr/local/bin/python3 /usr/local/bin/super_pwd $PWD)"
+function shorten_pwd() {
+  export SHORT_PWD="$(/usr/local/bin/python3 /usr/local/bin/super_pwd $PWD)"
 }
+
+chpwd_functions=(${chpwd_functions[@]} "shorten_pwd")
+
+function tmux_window_pwd() {
+  tmux rename-window "$SHORT_PWD"
+}
+precmd_functions=(${precmd_functions[@]} "tmux_window_pwd")
 
 eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib=$HOME/perl5)"
 
 homebrew_command_not_found_handle() {
-    local cmd="$1"
-    local txt="$(brew which-formula --explain $cmd 2>/dev/null)"
+  local cmd="$1"
+  local txt="$(brew which-formula --explain $cmd 2>/dev/null)"
 
-    if [ -z "$txt" ]; then
-        echo "zsh: command not found: $cmd" >&2
-    else
-        echo "$txt"
-    fi
+  if [ -z "$txt" ]; then
+    echo "zsh: command not found: $cmd" >&2
+  else
+    echo "$txt"
+  fi
 
-    return 127
+  return 127
 }
 
 command_not_found_handler() {
-    homebrew_command_not_found_handle $*
-    return $?
+  homebrew_command_not_found_handle $*
+  return $?
 }
-export PATH="/usr/local/opt/llvm/bin:$PATH"
+
 # Go development
 export GOPATH="${HOME}/.go"
-export GOROOT="$(brew --prefix golang)/libexec"
+export GOROOT="/usr/local/opt/golang/libexec"
 export PATH="$PATH:${GOPATH}/bin:${GOROOT}/bin"
 test -d "${GOPATH}" || mkdir "${GOPATH}"
 test -d "${GOPATH}/src/github.com" || mkdir -p "${GOPATH}/src/github.com"
 
-fpath+=${ZDOTDIR:-~}/.zsh_functions
+[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
+source ~/.dotfiles/zsh/shell_prompt.zsh
