What a mess

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -1,71 +1,30 @@
-CASE_SENSITIVE="true"
-if [[ `uname` == 'Linux'  ]]
-then
-  export LINUX=1
-  export GNU_USERLAND=1
-  export SHELL="/usr/bin/zsh"
-  if [[ -e "/usr/bin/tmux-next" ]]
-  then
-    export TMUX_PATH="/usr/bin/tmux-next"
-  else
-    export TMUX_PATH="/usr/bin/tmux"
-  fi
-else
-  export LINUX=
-fi
-
-if [[ `uname` == 'Darwin'  ]]
-then
-  export OSX=1
-  export SHELL="/usr/local/bin/zsh"
-  export TMUX_PATH="/usr/local/bin/tmux"
-else
-  export OSX=
-fi
-
-if [[ "$SSH_CONNECTION" ]]
-then
-  export REMOTE_SESSION=1
-else
-  export REMOTE_SESSION=
-fi
-
-export TRUE_COLOR=`$TMUX_PATH info | grep Tc | grep -o true`
-
 autoload run-help
-HELPDIR=/usr/local/share/zsh/help
-
-export PATH="$HOME/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin"
-
-if [[ -e /usr/local/bin/brew ]]
-then
-  export HOMEBREW_PREFIX="/usr/local"
-  export HOMEBREW_CELLAR="/usr/local/Cellar"
-  export HOMEBREW_REPOSITORY="/usr/local/Homebrew"
-  export MANPATH="/usr/local/share/man:$MANPATH"
-  export INFOPATH="/usr/local/share/info:$INFOPATH"
-  if [[ -e /usr/local/opt/coreutils ]]; then export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"; fi
-  if [[ -e /usr/local/opt/gnu-tar ]]; then export PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"; fi
-  if [[ -e /usr/local/opt/llvm ]]; then export PATH="/usr/local/opt/llvm/bin:$PATH"; fi
-  if [[ -e /usr/local/opt/python ]]; then export PATH="/usr/local/opt/python/libexec/bin:$PATH"; fi
-  export PATH="$HOME/.local/bin:$PATH"
-else
-fi
+HELPDIR=$PREFIX/share/zsh/help
 
 fpath+=${ZDOTDIR:-~}/.zsh_functions
-export DOTFILES=$HOME/.dotfiles
+ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=8'
+
 source $DOTFILES/zsh/private.zsh
 
-# google-cloud-sdk (homebrew)
-source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc'
-source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'
+export PYENV_ROOT="$HOME/.pyenv"
+export PATH="$PYENV_ROOT/bin:$PATH"
+if command -v pyenv 1>/dev/null 2>&1; then
+  eval "$(pyenv init --path)"
+fi
 
-# source '/usr/local/opt/asdf/asdf.sh'
-# source '/usr/local/opt/asdf/etc/bash_completion.d/asdf.bash'
+if [[ -e $HOMEBREW_PREFIX/bin/brew ]]
+then
+  [ -s "$HOMEBREW_PREFIX/opt/nvm/nvm.sh" ] && . "$HOMEBREW_PREFIX/opt/nvm/nvm.sh"  # This loads nvm
+  [ -s "$HOMEBREW_PREFIX/opt/nvm/etc/bash_completion.d/nvm" ] && . "$HOMEBREW_PREFIX/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
+else
+  [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
+  [ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
+fi
 
 source $HOME/antigen.zsh
 antigen init $HOME/.antigenrc
 
+alias brew='arch -arm64 brew'
 alias ls='ls -F --color=auto'
 #alias dir='dir --color=auto'
 #alias vdir='vdir --color=auto'
@@ -86,23 +45,9 @@ export LESSOPEN='|~/.lessfilter %s'
 
 alias yolo='git commit -am "$(curl -s https://whatthecommit.com/index.txt)"'
 
-if [[ -e `which nvim` ]]
-then
-  alias vim=nvim
-  export GIT_EDITOR=nvim
-  export VISUAL=nvim
-  export EDITOR=nvim
-else
-  export GIT_EDITOR=vim
-  export VISUAL=vim
-  export EDITOR=vim
-fi
-
-ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=8'
-
-export SHORT_PWD="$(/usr/local/bin/python3 /usr/local/bin/super_pwd $PWD)"
+export SHORT_PWD="$($SYS_PREFIX/bin/python3 $DOTFILES/bin/cwd.py $PWD)"
 function shorten_pwd() {
-  export SHORT_PWD="$(/usr/local/bin/python3 /usr/local/bin/super_pwd $PWD)"
+  export SHORT_PWD="$($SYS_PREFIX/bin/python3 $DOTFILES/bin/cwd.py $PWD)"
 }
 
 chpwd_functions=(${chpwd_functions[@]} "shorten_pwd")
@@ -112,14 +57,14 @@ function tmux_window_pwd() {
 }
 precmd_functions=(${precmd_functions[@]} "tmux_window_pwd")
 
-eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib=$HOME/perl5)"
+# eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib=$HOME/perl5)"
 
 homebrew_command_not_found_handle() {
   local cmd="$1"
   local txt="$(brew which-formula --explain $cmd 2>/dev/null)"
 
   if [ -z "$txt" ]; then
-    echo "zsh: command not found: $cmd" >&2
+    echo "command not found: $cmd" >&2
   else
     echo "$txt"
   fi
@@ -127,20 +72,14 @@ homebrew_command_not_found_handle() {
   return 127
 }
 
+export PATH=$PATH:~/.cargo/bin:~/go/bin
+
 command_not_found_handler() {
   homebrew_command_not_found_handle $*
   return $?
 }
 
-# Go development
-export GOPATH="${HOME}/.go"
-export GOROOT="/usr/local/opt/golang/libexec"
-export PATH="$PATH:${GOPATH}/bin:${GOROOT}/bin"
-test -d "${GOPATH}" || mkdir "${GOPATH}"
-test -d "${GOPATH}/src/github.com" || mkdir -p "${GOPATH}/src/github.com"
-
-export PYTHON_CONFIGURE_OPTS="--enable-framework"
-
 [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
+
 source ~/.dotfiles/zsh/shell_prompt.zsh
-export PATH="/usr/local/opt/openjdk@11/bin:$PATH"
+
